apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: vitaex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5.20.0
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: graph-secrets
                  key: auth
          ports:
            - containerPort: 7687
              name: bolt
            - containerPort: 7474
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: vitaex
spec:
  selector:
    app: neo4j
  ports:
    - name: bolt
      port: 7687
      targetPort: 7687
    - name: http
      port: 7474
      targetPort: 7474